apps:
  - name: sdxl_app_1
    script: /home/ubuntu/stable-diffusion-webui/launch.py
    interpreter: python
    args: "--listen --xformers --no-half-vae --reinstall-xformers --api --port 9838 --disable-safe-unpickle --enable-insecure-extension-access --ckpt /home/ubuntu/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors"
    time: true
    log_file: "sd_app.log"
    restart_delay: 15000
    merge_logs: false
    combine_logs: false